spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost:5432/movieflix
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

movieflix:
  security:
    secret: "KSALJDFLKAJSFDKJAL24895703475032473N245OI239N57923405320"